#put any key/value pairs here
my.plugin.name=MyPlugin
my-section.label=Export_CSV
my-web-item.name=My CSV Export Item
my-web-item.label=Export Data
my-web-item.description=Export project data
my-servlet.name=My Export Servlet
my-servlet.description=Handles export requests
